### ISSUE TITLE
Sometimes errors are returned when saving a document (No matching document found for id "5f58450f051a1cc9716a1f27")

### ISSUE THREAD

**Issue by sunshine173** [cesanta/mongoose#1146]
hi 
mongoose@5.0.1
mongodb@3.0.1
mongo db version 4.0.6
there no demo for you,  The error is about one out of every tens of thousands of requests

No matching document found for id "5f58450f051a1cc9716a1f27"
MongooseError: 
    at new MongooseError (/data/server/gameServer/node_modules/mongoose/lib/error/index.js:12:11)
    at model.Model.save (/data/server/gameServer/node_modules/mongoose/lib/model.js:328:25)

I confirm that the document exists
**I want to know the cause of this error and how to fix it**

**Comment by sunshine173** [comment]
wrong project
