### ISSUE TITLE
Multithread and SSL?

### ISSUE THREAD

**Issue by stromnet** [cesanta/mongoose#775]
I tried to use multithread + SSL in my app during upgrade to Mongoose 6.7, and got SIGSEGV on first SSL request.

Modified the simplest_server_ssl and added `mg_enable_multithreading(nc);` to test multithreading + SSL. 
Same crash. I guess it's not supported, but docs doesn't mention anything?

```
~/mongoose/examples/simplest_web_server_ssl$ gdb ./simplest_web_server_ssl
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) run
Starting program: 
~/mongoose/examples/simplest_web_server_ssl/simplest_web_server_ssl
[New LWP 102363]
Starting SSL server on port 8443, cert from server.pem, key from server.key
[New Thread 801c06800 (LWP 100443/simplest_web_server)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 801c06800 (LWP 100443/simplest_web_server)]
0x000000000040f3e7 in mg_ssl_if_read (nc=0x801c29480, buf=0x802011400, buf_size=1024) at ../../mongoose.c:4152
4152      int n = SSL_read(ctx->ssl, buf, buf_size);
Current language:  auto; currently minimal
(gdb) where
#0  0x000000000040f3e7 in mg_ssl_if_read (nc=0x801c29480, buf=0x802011400, buf_size=1024) at ../../mongoose.c:4152
#1  0x000000000040cd39 in mg_handle_tcp_read (conn=0x801c29480) at ../../mongoose.c:3401
#2  0x000000000040c790 in mg_mgr_handle_conn (nc=0x801c29480, fd_flags=1, now=1485203747.0017071) at ../../mongoose.c:3549
#3  0x000000000040df0b in mg_socket_if_poll (iface=0x80200f040, timeout_ms=1000) at ../../mongoose.c:3742
#4  0x00000000004086b0 in mg_mgr_poll (m=0x7fffdfffdf70, timeout_ms=1000) at ../../mongoose.c:2287
#5  0x000000000041f8ed in per_connection_thread_function (param=0x801c29480) at ../../mongoose.c:4716
#6  0x0000000800eb1855 in pthread_create () from /lib/libthr.so.3
#7  0x0000000000000000 in ?? ()
(gdb) print ctx
$1 = (struct mg_ssl_if_ctx *) 0x0
(gdb)
```

**Comment by cpq** [comment]
Please don't use multithreading API, we're removing it from the library.
